language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing to be installed"

before_scripts:
  - echo "no tests"

scripts:
  - docker --version 
  - docker build -t reverseproxy2 ./udagram-deployment/docker/
  - docker tag reverseproxy2 luancaius/reverseproxy2:latest

  - docker build -t udacity-restapi-user2 ./udagram-api-user/
  - docker tag udacity-restapi-user2 luancaius/udacity-restapi-user2:latest

  - docker build -t udacity-restapi-feed2 ./udagram-api-feed/
  - docker tag udacity-restapi-feed2 luancaius/udacity-restapi-feed2:latest

  - docker build -t udacity-frontend2 ./udagram-frontend/
  - docker tag udacity-frontend2 luancaius/udacity-frontend2:latest

after_success:
  - echo "using login for $DOCKER_USERNAME"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push luancaius/reverseproxy2:latest
  - docker push luancaius/udacity-restapi-user2:latest
  - docker push luancaius/udacity-restapi-feed2:latest
  - docker push luancaius/udacity-frontend2:latest
  - echo "Finished pushing images"