language: minimal

services:
  - docker

before_scripts:
  - echo "no tests"

install:
  - docker-compose -f udagram-deployment/docker/docker-compose-build.yaml build --parallel 

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push luancaius/reverseproxy2:latest
  - docker push luancaius/udacity-restapi-user2:latest
  - docker push luancaius/udacity-restapi-feed2:latest
  - docker push luancaius/udacity-frontend2:latest
  - echo "Finished pushing images"